export const DEFAULT_CALENDAR_DELIVERY_LIMIT = 120;

export const DEFAULT_WEEKLY_CALENDAR_DELIVERY_LIMITS: Record<string, number> = {
  sunday: DEFAULT_CALENDAR_DELIVERY_LIMIT,
  monday: DEFAULT_CALENDAR_DELIVERY_LIMIT,
  tuesday: DEFAULT_CALENDAR_DELIVERY_LIMIT,
  wednesday: DEFAULT_CALENDAR_DELIVERY_LIMIT,
  thursday: DEFAULT_CALENDAR_DELIVERY_LIMIT,
  friday: DEFAULT_CALENDAR_DELIVERY_LIMIT,
  saturday: DEFAULT_CALENDAR_DELIVERY_LIMIT,
};
